dependencies:
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.112
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.112
- alias: bdd-firstmicroservice
  name: postgresql
  repository: http://kubernetes-charts.storage.googleapis.com/
  version: 6.5.3
- name: firstmicroservice
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
